### ISSUE TITLE
User self-registration is gone once plugin is installed

### ISSUE THREAD

**Issue by pczekalski** [rztuc/dokuwiki-plugin-authchained#15]
I'm using `authchained` plugin along with `authad` (`authchained` forwards to `authad` and `authplain`, to let me inject non-ad users of Dokuwiki).
I'm able to login using AD and a locally created administrator user, however, the registration link that appears in the login dialog is gone.

How to re-enable it back? I cannot see any option in the config files to force-enable it back.

Regards,

P

**Comment by einhirn** [comment]
Did you set
```
$conf['plugin']['authchained']['usermanager_authtype'] = 'authplain';
```
(or the corresponding configuration option)?

Whether "authchained" "canDo" "addUser" depends on what the Plugin replies that's configured as "usermanager_authtype".

Or, maybe you just disabled the "register" action?

**Comment by pczekalski** [comment]
Thanks for the reply.
I've got "authad" in the "usermanager_authtype". I also acknowledge that register action is not disabled.

**Comment by einhirn** [comment]
Ok, there's your problem. Use "authplain" in "usermanager_authtype" and it'll work.

**Comment by pczekalski** [comment]
Works, thanks.
