### ISSUE TITLE
PHP Warning:  Declaration of auth_plugin_authchained...

### ISSUE THREAD

**Issue by Ratcreamsoup** [rztuc/dokuwiki-plugin-authchained#8]
I get messages such as these in my error log:

Got error 'PHP message: PHP Warning:  Declaration of auth_plugin_authchained::getUserData($user) should be compatible with DokuWiki_Auth_Plugin::getUserData($user, $requireGroups = true) in /var/www/dokuwiki/lib/plugins/authchained/auth.php on line 17\n'

I'm using PHP 7.0.30-0+deb9u1

**Comment by einhirn** [comment]
Hello Ratcreamsoup,

> I get messages such as these in my error log:
this issue is fixed since I merged the last pull request on 2017-06-24 but I didn't update the plugin info so the updater didn't notify you of a more current version...

Please check for update and install latest version. 

HTH
Einhirn

**Comment by j-trubini** [comment]
Hey, I am having the same issue causing my user getting logged out of session with each page refresh.

Running on Igor version, PHP Version 7.3.31-1~deb10u3

Any help?
